#------------------------------------------------------------------------------
# Module : Scorers
# Package: GamosCore_GamosScoring_Scorers
#
#------------------------------------------------------------------------------
#
set(CMAKE_VERBOSE_MAKEFILE ON)
include_directories(${CMAKE_SOURCE_DIR}/source)
include_directories(${CMAKE_SOURCE_DIR}/include)
#
# Define the GEANT4 Module.
include(UseGamosAtGeant4)
#
GEANT4_DEFINE_MODULE(NAME GamosCore_GamosScoring_Scorers
	 HEADERS
		GmG4PSEnergyLost.hh
		GmPSEnergyDeposit_VPrimaryGamma1stInter.hh
		GmG4PSDoseDeposit_old.hh
		GmG4PSPassageCellFlux.hh
		GmPSSurfaceFlux.hh
		GmPSCavityKwallOld.hh
		GmPSData.hh
		GmG4PSDoseDeposit.hh
		GmG4PSCellCharge.hh
		GmPSSphericalDoseDeposit.hh
		GmHistosAtCavityUA.hh
		GmPSLET_LETByESpect.hh
		GmPSLETBydEdxT.hh
		GmPSEnergyDeposit_PrimaryGammaAnyInter.hh
		GmG4PSDoseDepositVector.hh
		GmG4PSDoseDeposit_SkipEqualMateSimple.hh
		GmPSLET.hh
		GmPSCylindricalRZDoseDeposit.hh
		GmPSDose_LET.hh
		GmG4PSMinKinEAtGeneration.hh
		GmG4PSNofSecondary.hh
		GmG4PSPassageTrackLength.hh
		GmPSWithDirection.hh
		GmG4PSPopulation.hh
		GmG4PSKerma.hh
		GmPSCylindricalZPhiDoseDeposit.hh
		GmPSLETBydEdxD.hh
		GmPSDose_LETBydEdx.hh
		GmVScoringSurfaceSolid.hh
		GmPSLETBydEdx.hh
		GmPSVolumeFlux.hh
		GmPSCavityKatt.hh
		GmG4PSData.hh
		GmG4PSTermination.hh
		GmG4PSTrackCounter.hh
		GmPSEnergyDeposit_PrimaryGamma1stInter.hh
		GmPSEnergyDeposit_PrimaryGamma1stInterAttenuation.hh
		GmPSCylindricalRPhiDoseDeposit.hh
		GmG4PSEnergyDeposit.hh
		GmPSCavityKwall.hh
		GmG4PSPassageCellCurrent.hh
		GmPSLETByESpectD.hh
		GmScoringSurfaceOrb.hh
		GmPSLETEDepT.hh
		GmPSCavityKsc.hh
		GmScoringSurfaceSphere.hh
		GmPSLETByESpect.hh
		GmScoringSurfaceBox.hh
		GmG4PSDoseDeposit_NoSkipEqualMate.hh
		GmG4PSCellFlux.hh
		GmScoringSurfaceTubs.hh
		GmPSLETEDepD.hh
		GmG4PSNofStep.hh
		GmPSLETByESpectT.hh
		GmG4PSTrackLength.hh
		GmG4PSNofCollision.hh
		GmPSdx_LETBydEdx.hh
	 SOURCES
		GmG4PSDoseDeposit_NoSkipEqualMate.cc
		dd
		GmPSEnergyDeposit_PrimaryGamma1stInterAttenuation.cc
		GmPSEnergyDeposit_PrimaryGamma1stInter.cc
		plugin.cc
		GmPSdx_LETBydEdx.cc
		GmPSLETBydEdx.cc
		GmPSLET_LETByESpect.cc
		GmPSLETByESpectD.cc
		GmPSLET.cc
		GmPSLETBydEdxD.cc
		GmG4PSPassageCellFlux.cc
		GmG4PSPopulation.cc
		GmPSLETEDepT.cc
		GmPSLETEDepD.cc
		GmG4PSCellCharge.cc
		GmG4PSNofSecondary.cc
		GmScoringSurfaceSphere.cc
		GmG4PSTrackLength.cc
		GmHistosAtCavityUA.cc
		GmG4PSDoseDeposit.cc
		GmScoringSurfaceTubs.cc
		GmG4PSEnergyLost.cc
		GmVScoringSurfaceSolid.cc
		GmG4PSDoseDeposit_old.cc
		GmPSDose_LET.cc
		GmPSWithDirection.cc
		GmPSCylindricalRPhiDoseDeposit.cc
		GmPSCylindricalRZDoseDeposit.cc
		GmG4PSCellFlux.cc
		GmG4PSEnergyDeposit.cc
		GmPSCavityKwall.cc
		GmG4PSData.cc
		GmPSSurfaceFlux.cc
		GmG4PSPassageCellCurrent.cc
		GmPSLETByESpect.cc
		GmG4PSDoseDeposit_SkipEqualMateSimple.cc
		GmPSEnergyDeposit_PrimaryGammaAnyInter.cc
		GmPSSphericalDoseDeposit.cc
		GmPSLETBydEdxT.cc
		GmPSCavityKatt.cc
		GmPSEnergyDeposit_VPrimaryGamma1stInter.cc
		GmG4PSPassageTrackLength.cc
		GmG4PSNofStep.cc
		GmG4PSTermination.cc
		GmScoringSurfaceOrb.cc
		GmPSCylindricalZPhiDoseDeposit.cc
		GmPSDose_LETBydEdx.cc
		GmG4PSKerma.cc
		GmPSCavityKsc.cc
		GmG4PSMinKinEAtGeneration.cc
		GmPSData.cc
		GmG4PSNofCollision.cc
		GmG4PSTrackCounter.cc
		GmPSCavityKwallOld.cc
		GmPSVolumeFlux.cc
		GmG4PSDoseDepositVector.cc
		GmScoringSurfaceBox.cc
		GmPSLETByESpectT.cc
	 
	 GRANULAR_DEPENDENCIES
	 GLOBAL_DEPENDENCIES
		${Geant4_libs} 
		${ROOT_LIBRARIES} 
	GamosCore_GamosUtils
	GamosCore_GamosBase_Base
	GamosCore_GamosGeometry
	GamosCore_GamosReadDICOM
	GamosCore_GamosGenerator
	GamosCore_GamosData_Management
	GamosCore_GamosData_Users
	GamosCore_GamosScoring_Management
	GamosCore_GamosData_Distributions
		${SEAL_LIBRARIES} 

	LINK_LIBRARIES
)
