# - GamosCore_GamosScoring_Scorers module build definition

include(UseGamosAtGeant4)
include(UseROOT)

geant4_add_module(GamosCore_GamosScoring_Scorers
  PUBLIC_HEADERS
    GmPSCylindricalRPhiDoseDeposit.hh
    GmPSLET_dEdx_unrestrD.hh
    GmPSLET_LETESpect.hh
    GmPSEnergyDeposit_VPrimaryGamma1stInter.hh
    GmPSWithDirection.hh
    GmPSRBEPhenom_Carabe.hh
    GmG4PSTermination.hh
    GmVScoringSurfaceSolid.hh
    GmPSConstant.hh
    GmPSdEdxElectronicELoss.hh
    GmPSLET_EDepD.hh
    GmPSElectronicdEdx.hh
    GmG4PSDoseDepositVector.hh
    GmPSLET_dEdx_unrestrT.hh
    GmG4PSCellCharge.hh
    GmPSdx_LET_dEdx.hh
    GmG4PSNofCollision.hh
    GmPSdx_LET_dEdx_unrestr.hh
    GmG4PSNofSecondary.hh
    GmG4PSMinKinEAtGeneration.hh
    GmScoringSurfaceSphere.hh
    GmPSSphericalDoseDeposit.hh
    GmG4PSEnergyLoss.hh
    GmG4PSDoseDeposit_old.hh
    GmG4PSNofStep.hh
    GmG4PSPassageCellFlux.hh
    GmPSElectronicELoss.hh
    GmG4PSTrackCounter.hh
    GmG4PSPassageCellCurrent.hh
    GmPSSurfaceFlux.hh
    GmPSEquivDose.hh
    GmG4PSDoseDeposit_NoSkipEqualMate.hh
    GmComputeDEDX.hh
    GmG4PSPassageTrackLength.hh
    GmPSDose_LET_EDep.hh
    GmPSLET_ESpectD.hh
    GmScoringSurfaceOrb.hh
    GmPSLET_dEdxD.hh
    GmPSLET_dEdx_unrestr.hh
    GmPSCylindricalRZDoseDeposit.hh
    GmPSLET_EDep.hh
    GmScoringSurfaceTubs.hh
    GmPSDose_LET_dEdx.hh
    GmPSLET_dEdx.hh
    GmPSLET_ESpect.hh
    GmPSCylindricalZPhiDoseDeposit.hh
    GmG4PSDoseDeposit.hh
    GmComputeRBEPhenom.hh
    GmHistosAtCavityUA.hh
    GmG4PSDoseDeposit_SkipEqualMateSimple.hh
    GmPSDose_LET_dEdx_unrestr.hh
    GmPSLET_ESpectT.hh
    GmPSEnergyDeposit_PrimaryGammaAnyInter.hh
    GmPSEnergyDeposit_PrimaryGamma1stInter.hh
    GmG4PSEnergyDeposit.hh
    GmPSVolumeFlux.hh
    GmPSDEDX.hh
    GmPSLET_EDepT.hh
    GmScoringSurfaceBox.hh
    GmPSData.hh
    kk
    GmG4PSPopulation.hh
    GmPSEnergyDeposit_PrimaryGamma1stInterAttenuation.hh
    GmPSLET_dEdxT.hh
    GmG4PSCellFlux.hh
    GmG4PSData.hh
    GmG4PSKerma.hh
    GmG4PSTrackLength.hh
  SOURCES
    GmPSLET_EDep.cc
    GmPSLET_dEdxD.cc
    GmPSEnergyDeposit_PrimaryGamma1stInter.cc
    GmPSLET_EDepT.cc
    GmHistosAtCavityUA.cc
    GmPSLET_dEdxT.cc
    GmG4PSPassageTrackLength.cc
    GmPSLET_ESpectT.cc
    GmG4PSTermination.cc
    GmPSLET_ESpect.cc
    GmPSLET_LETESpect.cc
    GmPSCylindricalZPhiDoseDeposit.cc
    GmPSSurfaceFlux.cc
    GmG4PSPopulation.cc
    GmG4PSDoseDeposit_SkipEqualMateSimple.cc
    GmPSLET_EDepD.cc
    GmPSData.cc
    GmPSEnergyDeposit_PrimaryGamma1stInterAttenuation.cc
    GmPSCylindricalRPhiDoseDeposit.cc
    GmG4PSDoseDeposit_old.cc
    GmG4PSDoseDeposit.cc
    GmPSdx_LET_dEdx.cc
    GmG4PSNofStep.cc
    GmG4PSPassageCellCurrent.cc
    GmPSDEDX.cc
    GmPSdEdxElectronicELoss.cc
    GmPSdx_LET_dEdx_unrestr.cc
    GmPSDose_LET_dEdx_unrestr.cc
    GmPSWithDirection.cc
    GmScoringSurfaceSphere.cc
    GmPSEnergyDeposit_PrimaryGammaAnyInter.cc
    GmG4PSNofSecondary.cc
    GmComputeDEDX.cc
    GmPSElectronicELoss.cc
    GmG4PSTrackLength.cc
    GmPSEquivDose.cc
    GmPSEnergyDeposit_VPrimaryGamma1stInter.cc
    plugin.cc
    GmPSRBEPhenom_Carabe.cc
    GmG4PSTrackCounter.cc
    GmScoringSurfaceBox.cc
    GmG4PSDoseDeposit_NoSkipEqualMate.cc
    plugin.cc.old
    GmComputeDEDX.doc
    GmScoringSurfaceTubs.cc
    GmG4PSDoseDepositVector.cc
    plugin.cc.new
    GmPSElectronicdEdx.cc
    ff
    GmG4PSCellFlux.cc
    GmPSConstant.cc
    GmG4PSCellCharge.cc
    GmComputeRBEPhenom.cc
    GmPSCylindricalRZDoseDeposit.cc
    GmG4PSEnergyDeposit.cc
    GmPSVolumeFlux.cc
    GmPSDose_LET_EDep.cc
    kk
    GmPSLET_ESpectD.cc
    GmG4PSEnergyLoss.cc
    GmG4PSPassageCellFlux.cc
    GmPSSphericalDoseDeposit.cc
    GmPSLET_dEdx_unrestrD.cc
    GmPSLET_dEdx.cc
    GmPSDose_LET_dEdx.cc
    GmScoringSurfaceOrb.cc
    GmG4PSData.cc
    GmPSLET_dEdx_unrestr.cc
    GmPSLET_dEdx_unrestrT.cc
    GmG4PSNofCollision.cc
    GmVScoringSurfaceSolid.cc
    GmG4PSMinKinEAtGeneration.cc
    GmG4PSKerma.cc
)
# - Add path to generated header
geant4_module_include_directories(GamosCore_GamosScoring_Scorers
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63>
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63/SEAL_Foundation/SealBase/include>
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63/SEAL_Foundation/SealPlatform/include>
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63/SEAL_Foundation/PluginManager/include>
 PUBLIC  $<BUILD_INTERFACE:${ROOT_BASE_DIR}/include>)

geant4_module_link_libraries(GamosCore_GamosScoring_Scorers
  PUBLIC
    ${Geant4_libs}
    ${ROOT_LIBRARIES}
    ${SEAL_LIBRARIES} 
    GamosCore_GamosUtils
    GamosCore_GamosBase_Base
    GamosCore_GamosGeometry
    GamosCore_GamosReadDICOM
    GamosCore_GamosGenerator
    GamosCore_GamosData_Management
    GamosCore_GamosData_Users
    GamosCore_GamosScoring_Management
    GamosCore_GamosData_Distributions
)
