include $(GAMOSINSTALL)/config/architecture.gmk

SUBDIRS  = DICOM2G4 getOrganInfo drawDICOM getGammaIndex changeStructure printValueAtPoint printValueAlongLine GamosToDICOM resizeImage dcmdump getImageValue

include $(GAMOSINSTALL)/config/globlib.gmk

