#------------------------------------------------------------------------------
# Module : Users
# Package: GamosCore_GamosData_Users
#
#------------------------------------------------------------------------------
#
set(CMAKE_VERBOSE_MAKEFILE ON)
include_directories(${CMAKE_SOURCE_DIR}/source)
include_directories(${CMAKE_SOURCE_DIR}/include)
#
# Define the GEANT4 Module.
include(UseGamosAtGeant4)
#
GEANT4_DEFINE_MODULE(NAME GamosCore_GamosData_Users
	 HEADERS
		GmStackDataCoutUA.hh
		GmStepDataTextFileUA.hh
		GmStepDataCoutUA.hh
		GmEventDataBinFileUA.hh
		GmVDataUserTextFile.hh
		GmSecondaryTrackDataTextFileUA.hh
		GmTrackDataCoutUA.hh
		GmTrackDataTextFileUA.hh
		GmSecondaryTrackDataHistosUA.hh
		GmStackDataBinFileUA.hh
		GmNumericDataFilter.hh
		GmClassifierByDistribution.hh
		GmStepDataBinFileUA.hh
		GmVDataUserHistos.hh
		GmSecondaryTrackDataBinFileUA.hh
		GmClassifierByNumericData.hh
		GmRunDataTextFileUA.hh
		GmRunDataHistosUA.hh
		GmEventDataCoutUA.hh
		GmTrackDataBinFileUA.hh
		GmStackDataTextFileUA.hh
		GmEventDataHistosUA.hh
		GmRunDataCoutUA.hh
		GmEventDataTextFileUA.hh
		GmDataTTreeUA.hh
		GmTrackDataHistosUA.hh
		GmClassifierByStringData.hh
		GmSecondaryTrackDataCoutUA.hh
		GmStringDataFilter.hh
		GmVDataUserBinFile.hh
		GmRunDataBinFileUA.hh
		GmStackDataHistosUA.hh
		GmStepDataHistosUA.hh
		GmVDataUser.hh
	 SOURCES
		GmTrackDataCoutUA.cc
		GmTrackDataHistosUA.cc
		plugin.cc
		GmEventDataHistosUA.cc
		GmDataTTreeUA.cc
		GmStackDataBinFileUA.cc
		GmStepDataHistosUA.cc
		GmRunDataTextFileUA.cc
		GmEventDataCoutUA.cc
		GmStackDataHistosUA.cc
		GmClassifierByNumericData.cc
		GmTrackDataTextFileUA.cc
		GmClassifierByDistribution.cc
		GmRunDataHistosUA.cc
		GmClassifierByStringData.cc
		GmVDataUser.cc
		GmVDataUserTextFile.cc
		GmSecondaryTrackDataCoutUA.cc
		GmSecondaryTrackDataTextFileUA.cc
		GmEventDataBinFileUA.cc
		GmStackDataCoutUA.cc
		GmStepDataTextFileUA.cc
		GmTrackDataBinFileUA.cc
		GmSecondaryTrackDataBinFileUA.cc
		GmNumericDataFilter.cc
		GmVDataUserBinFile.cc
		GmEventDataTextFileUA.cc
		GmVDataUserHistos.cc
		GmSecondaryTrackDataHistosUA.cc
		GmStringDataFilter.cc
		GmRunDataBinFileUA.cc
		GmStepDataBinFileUA.cc
		GmRunDataCoutUA.cc
		GmStepDataCoutUA.cc
		GmStackDataTextFileUA.cc
	 
	 GRANULAR_DEPENDENCIES
	 GLOBAL_DEPENDENCIES
		${Geant4_libs} 
		${ROOT_LIBRARIES} 
		${SEAL_LIBRARIES} 
		GamosCore_GamosBase_Base
		GamosCore_GamosData_Management
		GamosCore_GamosAnalysis
		GamosCore_GamosBase_Classifiers
		GamosCore_GamosBase_Filters

	LINK_LIBRARIES
)
