#------------------------------------------------------------------------------
# Module : PhysicsList
# Package: GamosCore_GamosPhysics_PhysicsList
#
#------------------------------------------------------------------------------
#
set(CMAKE_VERBOSE_MAKEFILE ON)
include_directories(${CMAKE_SOURCE_DIR}/source)
include_directories(${CMAKE_SOURCE_DIR}/include)
#
# Define the GEANT4 Module.
include(UseGamosAtGeant4)
#
GEANT4_DEFINE_MODULE(NAME GamosCore_GamosPhysics_PhysicsList
	 HEADERS
		GmPhysicsDecay.hh
		GmPhysicsCerenkov.hh
		GmPhysicsFactory.hh
		GmAcollinearEplusAnnihilation.hh
		GmPhysicsVerbosity.hh
		GmPhysicsXrayRefraction.hh
		LocalIonIonInelasticPhysic.hh
		GmPhysicsElectronLowEner.hh
		GmPhysicsGammaNuclear.hh
		GmPEEffectFluoModel_XSChange.hh
		GmComptonScattering_XSChange.hh
		GmPhysicsElectronNuclear.hh
		GmRadiotherapyPhysics.hh
		GmGammaConversion_XSChange.hh
		GmPhysicsGammaPenelope.hh
		GmPhysicsGammaLowEner.hh
		GmPhysicsElectronPenelope.hh
		GmPhysicsGammaStandard_XSChange.hh
		GmEMPhysicsMessenger.hh
		GmEMStandardPhysicsMessenger.hh
		GmXrayRefraction.hh
		GmPhysicsMuonStandard.hh
		GmPhysicsGammaStandard.hh
		HadrontherapyStepMaxMessenger.hh
		GmLivermoreRayleighModel_XSChange.hh
		GmPhysicsPositronNuclear.hh
		GmPhysicsPositronStandard.hh
		HadrontherapyStepMax.hh
		GmPhysicsParallel.hh
		GmKleinNishinaCompton_XSChange.hh
		HadrontherapyPhysics.hh
		GmEMPhysics.hh
		GmPhysicsOpticalPhoton.hh
		GmXSChange_DistributionUser.hh
		GmLivermoreRayleighModel_XSChangeNEW.hh
		GmPhysicsElectronStandard.hh
		HadrontherapyPhysicsMessenger.hh
		GmPhysicsRadioactiveDecay.hh
		GmPhysicsCoulombScattering.hh
		GmPhotoElectricEffect_XSChange.hh
		GmEMExtendedPhysics.hh
		GmRayleighScattering_XSChange.hh
		GmPhysicsMultipleScattering.hh
		GmExtraPhysicsMessenger.hh
		GmVPhysicsElectron.hh
		GmEMStandardPhysics.hh
		GmVPhysicsGamma.hh
		GmPhysicsPositronPenelope.hh
		GmBetheHeitlerModel_XSChange.hh
	 SOURCES
		GmAcollinearEplusAnnihilation.cc
		plugin.cc
		GmPhysicsGammaStandard.cc
		GmXSChange_DistributionUser.cc
		GmPhysicsElectronStandard.cc
		GmPhysicsGammaLowEner.cc
		GmPhysicsFactory.cc
		GmVPhysicsGamma.cc
		HadrontherapyStepMax.cc
		GmRadiotherapyPhysics.cc
		GmPhysicsPositronNuclear.cc
		GmEMPhysics.cc
		GmPhysicsPositronPenelope.cc
		GmPhysicsDecay.cc
		HadrontherapyPhysics.cc
		GmPhysicsMuonStandard.cc
		GmEMStandardPhysicsMessenger.cc
		GmPhysicsGammaPenelope.cc
		GmPEEffectFluoModel_XSChange.cc
		GmPhysicsElectronPenelope.cc
		GmRayleighScattering_XSChange.cc
		GmPhysicsVerbosity.cc
		GmEMStandardPhysics.cc
		GmEMPhysicsMessenger.cc
		GmPhysicsGammaNuclear.cc
		GmPhysicsParallel.cc
		GmGammaConversion_XSChange.cc
		GmPhotoElectricEffect_XSChange.cc
		GmPhysicsCoulombScattering.cc
		GmKleinNishinaCompton_XSChange.cc
		GmEMExtendedPhysics.cc
		GmLivermoreRayleighModel_XSChange.cc
		GmXrayRefraction.cc
		GmComptonScattering_XSChange.cc
		GmBetheHeitlerModel_XSChange.cc
		HadrontherapyStepMaxMessenger.cc
		GmExtraPhysicsMessenger.cc
		LocalIonIonInelasticPhysic.cc
		GmPhysicsElectronNuclear.cc
		GmPhysicsElectronLowEner.cc
		GmPhysicsMultipleScattering.cc
		GmVPhysicsElectron.cc
		HadrontherapyPhysicsMessenger.cc
		GmPhysicsOpticalPhoton.cc
		GmPhysicsCerenkov.cc
		GmPhysicsPositronStandard.cc
		GmPhysicsGammaStandard_XSChange.cc
		GmLivermoreRayleighModel_XSChangeNEW.cc
		GmPhysicsXrayRefraction.cc
		GmPhysicsRadioactiveDecay.cc
		
	 GRANULAR_DEPENDENCIES
	 GLOBAL_DEPENDENCIES
		${Geant4_libs} 
		${ROOT_LIBRARIES} 
	GamosCore_GamosUtils
	GamosCore_GamosBase_Base
		${SEAL_LIBRARIES} 

	LINK_LIBRARIES
)
