#------------------------------------------------------------------------------
# Module : GamosReadDICOM
# Package: GamosCore_GamosReadDICOM
#
#------------------------------------------------------------------------------
#
set(CMAKE_VERBOSE_MAKEFILE ON)
include_directories(${CMAKE_SOURCE_DIR}/source)
include_directories(${CMAKE_SOURCE_DIR}/include)
#
# Define the GEANT4 Module.
include(UseGamosAtGeant4)
#
GEANT4_DEFINE_MODULE(NAME GamosCore_GamosReadDICOM
	 HEADERS
		GmDumpMateG4dcmUA.hh
		GmReadPhantomStMgr.hh
		GmGenerDistPositionInPhantomVoxels.hh
		GmReadPhantomG4withStGeometry.hh
		GmTouchablePhantomStructure.hh
		GmClassifierByPhantomStructure.hh
		GmReadPhantomPartialG4Geometry.hh
		Gm3ddose.hh
		GmReadPhantomEGSwithStGeometry.hh
		GmGenerDistPositionInStPhantomVoxels.hh
		GmBuildPhantomStructuresUA.hh
		GmReadPhantomEGSGeometry.hh
		GmSimplePhantomGeometry.hh
		GmReadNMDicom.hh
		GmReadPETDicom.hh
		GmGenerDistPositionPETImage.hh
		GmSqdoseHeader.hh
		GmClassifierCrossPhantom.hh
		DicomNestedPhantomParameterisation.hh
		GmReadPhantomG4BinGeometry.hh
		Gm3ddoseHeader.hh
		GmReadPhantomPSMgr.hh
		GmSqdose.hh
		GmPhantomStructures.hh
		GmRegularParamUtils.hh
		GmReadPhantomG4Geometry.hh
		GmGenerDistPositionNMImage.hh
		GmPhantomDensityHistosUA.hh
		GmPhantomDoseUA.hh
		GmReadDICOMVerbosity.hh
		GmCrossPhantomGeometry.hh
	 SOURCES
		GmCrossPhantomGeometry.cc
		GmSqdoseHeader.cc
		plugin.cc
		GmGenerDistPositionInStPhantomVoxels.cc
		GmBuildPhantomStructuresUA.cc
		GmReadPhantomEGSwithStGeometry.cc
		GmReadPhantomStMgr.cc
		GmSimplePhantomGeometry.cc
		GmReadPhantomG4Geometry.cc
		GmGenerDistPositionPETImage.cc
		GmGenerDistPositionInPhantomVoxels.cc
		Gm3ddose.cc
		GmPhantomDoseUA.cc
		GmReadPhantomEGSGeometry.cc
		GmReadPhantomPartialG4Geometry.cc
		GmClassifierCrossPhantom.cc
		GmReadPhantomPSMgr.cc
		GmPhantomDensityHistosUA.cc
		GmSqdose.cc
		GmReadDICOMVerbosity.cc
		GmClassifierByPhantomStructure.cc
		GmReadPhantomG4BinGeometry.cc
		GmDumpMateG4dcmUA.cc
		GmGenerDistPositionNMImage.cc
		DicomNestedPhantomParameterisation.cc
		GmReadPhantomG4withStGeometry.cc
		GmRegularParamUtils.cc
		GmReadNMDicom.cc
		GmReadPETDicom.cc
		GmTouchablePhantomStructure.cc
		Gm3ddoseHeader.cc
	 
	 GRANULAR_DEPENDENCIES
	 GLOBAL_DEPENDENCIES
		${Geant4_libs} 
		${ROOT_LIBRARIES} 
	GamosCore_GamosBase_Base
	GamosCore_GamosUserActionMgr
	GamosCore_GamosGeometry
	GamosCore_GamosUtils
	GamosCore_GamosBase_Filters
	GamosCore_GamosGenerator
		${SEAL_LIBRARIES} 

	LINK_LIBRARIES
)
