#------------------------------------------------------------------------------
# Module : Base
# Package: GamosCore_GamosBase_Base
#
#------------------------------------------------------------------------------
#
set(CMAKE_VERBOSE_MAKEFILE ON)
# Define the GEANT4 Module.
include(Geant4MacroDefineModule)
include(Geant4Libs)
include(UseGamosAtGeant4)
#
#
GEANT4_DEFINE_MODULE(NAME GamosCore_GamosBase_Base
	 HEADERS
		GmChangeEnergies.hh
		GmBaseVerbosity.hh
		GmHistoWriterGraphics.hh
		GmVisManager.hh
		GmHisto1.hh
		GmParameterList.hh
		GmVerbosityFactory.hh
		GmUIcmdWithAString.hh
		GmGetParticleMgr.hh
		GmAnalysisMgr.hh
		GmVDistribution.hh
		GmHistoProfile1.hh
		GmParameterList.icc
		GmHisto2.hh
		GmBaseMessenger.hh
		GmParameterListNumeric.icc
		GmParameterListVNumeric.icc
		GmParameter.hh
		GmParameterMgr.hh
		GmVVerbosity.hh
		GmClassifierMgr.hh
		GmVFilter.hh
		GmHistoWriter.hh
		GmDistributionMgr.hh
		GmIObinMgr.hh
		GmParameterListNumeric.hh
		GmAnalysisMessenger.hh
		GmVClassifier.hh
		GmHistoReaderCSV.hh
		GmHistoWriterROOT.hh
		GmTrackInfo.hh
		GmIOMgr.hh
		GmClassifierFactory.hh
		GmFilterMgr.hh
		GmFilterFactory.hh
		GmDistributionFactory.hh
		GmIOtextMgr.hh
		GmParameterMessenger.hh
		GmHistoWriterCSV.hh
		GmParameterListVNumeric.hh
		GmHistoWriterTXT.hh
		GmConvergenceTester.hh
		GmHistoProfile2.hh
	 SOURCES
		GmHisto1.cc
		GmIOtextMgr.cc
		GmUIcmdWithAString.cc
		plugin.cc
		GmParameterMessenger.cc
		GmHistoWriterTXT.cc
		GmIObinMgr.cc
		GmBaseMessenger.cc
		GmFilterMgr.cc
		GmParameterMgr.cc
		GmClassifierMgr.cc
		GmConvergenceTester.cc
		GmChangeEnergies.cc
		GmVVerbosity.cc
		GmHistoProfile2.cc
		GmHistoProfile1.cc
		GmHistoWriterCSV.cc
		GmVerbosityFactory.cc
		GmDistributionMgr.cc
		GmHistoWriterGraphics.cc
		GmTrackInfo.cc
		GmBaseVerbosity.cc
		GmHistoWriterROOT.cc
		GmHisto2.cc
		GmVClassifier.cc
		GmFilterFactory.cc
		GmGetParticleMgr.cc
		GmHistoReaderCSV.cc
		GmClassifierFactory.cc
		GmVDistribution.cc
		GmAnalysisMessenger.cc
		GmIOMgr.cc
		GmVFilter.cc
		GmAnalysisMgr.cc
		GmDistributionFactory.cc
	 
	 GRANULAR_DEPENDENCIES
	 GLOBAL_DEPENDENCIES
		${GEANT4_LIBRARIES} 
		${Geant4_libs} 
		${ROOT_LIBRARIES} 
    	${SEAL_LIBRARIES} 
		GamosCore_GamosUtils
		
	LINK_LIBRARIES
)
