#------------------------------------------------------------------------------
# Module : Filters
# Package: GamosCore_GamosBase_Filters
#
#------------------------------------------------------------------------------
#
set(CMAKE_VERBOSE_MAKEFILE ON)
include_directories(${CMAKE_SOURCE_DIR}/source)
include_directories(${CMAKE_SOURCE_DIR}/include)
#
# Define the GEANT4 Module.
include(UseGamosAtGeant4)
#
GEANT4_DEFINE_MODULE(NAME GamosCore_GamosBase_Filters
	 HEADERS
		GmFilterFromClassifier.hh
		GmVVolumeConditionFilter.icc
		GmInPhysicalVolumeChildrenFilter.hh
		GmInMassRegionFilter.hh
		GmVertexKineticEnergyFilter.hh
		GmTraverseParallelPhysicalVolumeFilter.hh
		GmGeomConditionTraverse.hh
		GmStartParallelPhysicalVolumeFilter.hh
		GmTouchableFilterRegion.hh
		GmHistoryAncestorsAllFilter.hh
		GmEnterPhysicalVolumeFilter.hh
		GmMaterialFilter.hh
		GmStartRegionFilter.hh
		GmGeomConditionEnter.hh
		GmInParallelPhysicalVolumeReplicatedFilter.hh
		GmSameLogicalVolumeFilter.hh
		GmTouchableFilterLogicalVolume.hh
		GmEndRegionChildrenFilter.hh
		GmPrimaryFilter.hh
		GmNeutronFilter.hh
		GmGeomConditionTraverseParallel.hh
		GmExitTouchableChildrenFilter.hh
		GmGeomConditionEnterParallel.hh
		GmTouchableFilterPhysicalVolumeReplicatedChildren.hh
		GmStartTouchableFilter.hh
		GmExitLogicalVolumeChildrenFilter.hh
		GmOnSecondaryFilter.hh
		GmTraverseLogicalVolumeChildrenFilter.hh
		GmEnterRegionChildrenFilter.hh
		GmParticleProcessFilter.hh
		GmExitParallelLogicalVolumeFilter.hh
		GmExitLogicalVolumeFilter.hh
		GmPositionPreYFilter.hh
		GmStartLogicalVolumeFilter.hh
		GmStartTouchableChildrenFilter.hh
		GmExitPhysicalVolumeFilter.hh
		GmPositionXFilter.hh
		GmProdCutAllProcOutsideVoxelFilter.hh
		GmTraversePhysicalVolumeChildrenFilter.hh
		GmEndParallelPhysicalVolumeFilter.hh
		GmInLogicalVolumeFilter.hh
		GmVVolumeConditionFilter.hh
		GmHistoryOrAncestorsFilter.hh
		GmInPhysicalVolumeReplicatedFilter.hh
		GmEndPhysicalVolumeFilter.hh
		GmDifferentLogicalVolumeFilter.hh
		GmEnergyChangeFilter.hh
		GmEnterParallelPhysicalVolumeReplicatedFilter.hh
		GmEndRegionFilter.hh
		GmEndParallelPhysicalVolumeReplicatedFilter.hh
		GmGeomConditionExitParallel.hh
		GmGeomConditionInParallel.hh
		GmSecondaryFilter.hh
		GmKineticEnergyFilter.hh
		GmParentFilter.hh
		GmTouchableFilterRegionChildren.hh
		GmXORFilter.hh
		GmElectronOrPositronFilter.hh
		GmVFilterOfFilters.hh
		GmVolumeFilters.hh
		GmGeomConditionStartParallel.hh
		GmEndPhysicalVolumeReplicatedFilter.hh
		GmEndLogicalVolumeChildrenFilter.hh
		GmFilterVerbosity.hh
		GmPositronFilter.hh
		GmEnterPhysicalVolumeChildrenFilter.hh
		GmInverseFilter.hh
		GmEnterPhysicalVolumeChildrenReplicatedFilter.hh
		GmEndPhysicalVolumeChildrenReplicatedFilter.hh
		GmTouchableFilterLogicalVolumeChildren.hh
		GmExitRegionChildrenFilter.hh
		GmEnterParallelPhysicalVolumeFilter.hh
		GmGeomConditionExit.hh
		GmTraverseParallelRegionFilter.hh
		GmDirectionThetaFilter.hh
		GmNeutralFilter.hh
		GmExitParallelPhysicalVolumeFilter.hh
		GmPositionZFilter.hh
		GmStartPhysicalVolumeFilter.hh
		GmGeomConditionStart.hh
		GmInParallelLogicalVolumeFilter.hh
		GmInTouchableFilter.hh
		GmEndPhysicalVolumeChildrenFilter.hh
		GmTraversePhysicalVolumeChildrenReplicatedFilter.hh
		GmEndLogicalVolumeFilter.hh
		GmChargedFilter.hh
		GmGeomConditionIn.hh
		GmStartPhysicalVolumeChildrenFilter.hh
		GmTouchableFilterTouchableChildren.hh
		GmTraverseParallelLogicalVolumeFilter.hh
		GmHistoryAllFilter.hh
		GmTraverseTouchableChildrenFilter.hh
		GmDirectionPhiFilter.hh
		GmEndParallelLogicalVolumeFilter.hh
		GmDepositedEnergyFilter.hh
		GmAncestorsFilter.hh
		GmEnterLogicalVolumeChildrenFilter.hh
		GmPositionPreZFilter.hh
		GmInPhysicalVolumeChildrenReplicatedFilter.hh
		GmExitParallelRegionFilter.hh
		GmInParallelPhysicalVolumeFilter.hh
		GmStartParallelPhysicalVolumeReplicatedFilter.hh
		GmPhysicalVolumeFilter.hh
		GmExitPhysicalVolumeReplicatedFilter.hh
		GmMinRangeCutOutsideVoxelFilter.hh
		GmTouchableFilterPhysicalVolume.hh
		GmGeomConditionEndParallel.hh
		GmInTouchableChildrenFilter.hh
		GmHistoryFilter.hh
		GmEnterPhysicalVolumeReplicatedFilter.hh
		GmGeomConditionEnd.hh
		GmVProdCutOutsideVoxelFilter.hh
		GmVParallelGeomCondition.hh
		GmTraverseTouchableFilter.hh
		GmEnterTouchableChildrenFilter.hh
		GmExitPhysicalVolumeChildrenReplicatedFilter.hh
		GmInteractionFilter.hh
		GmProtonFilter.hh
		GmVParallelVolumeConditionFilter.icc
		GmTraversePhysicalVolumeReplicatedFilter.hh
		GmExitParallelPhysicalVolumeReplicatedFilter.hh
		GmInMassPhysicalVolumeReplicatedFilter.hh
		GmVGeomCondition.hh
		GmEnterParallelLogicalVolumeFilter.hh
		GmGeomConditionInMass.hh
		GmStartPhysicalVolumeChildrenReplicatedFilter.hh
		GmDirectionPreThetaFilter.hh
		GmVTouchableFilterVolume.hh
		GmVANDFilter.hh
		GmPastHistoryFilter.hh
		GmEnterRegionFilter.hh
		GmTraverseRegionFilter.hh
		GmHistoryOrAncestorsFilterForScorer.hh
		GmStepNumberFilter.hh
		GmEnterTouchableFilter.hh
		GmCreatorProcessFilter.hh
		GmExitRegionFilter.hh
		GmEnterLogicalVolumeFilter.hh
		GmStartParallelRegionFilter.hh
		GmInParallelRegionFilter.hh
		GmPostKineticEnergyFilter.hh
		GmEndTouchableFilter.hh
		GmInMassPhysicalVolumeFilter.hh
		GmInRegionFilter.hh
		GmPrimaryOn1SecondaryFilter.hh
		GmStartRegionChildrenFilter.hh
		GmProcessFilter.hh
		GmNumberOfSecondariesFilter.hh
		GmParticleFilter.hh
		GmProdCutOutsideVoxelFilter.hh
		GmDirectionPrePhiFilter.hh
		GmTouchableFilterTouchable.hh
		GmExitTouchableFilter.hh
		GmORFilter.hh
		GmInLogicalVolumeChildrenFilter.hh
		GmANDFilter.hh
		GmEnterParallelRegionFilter.hh
		GmTraversePhysicalVolumeFilter.hh
		GmStartPhysicalVolumeReplicatedFilter.hh
		GmDeltaEnergyFilter.hh
		GmInRegionChildrenFilter.hh
		GmEndTouchableChildrenFilter.hh
		GmEndParallelRegionFilter.hh
		GmExitPhysicalVolumeChildrenFilter.hh
		GmPositionYFilter.hh
		GmTraverseRegionChildrenFilter.hh
		GmElectronFilter.hh
		GmTouchableFilterPhysicalVolumeChildren.hh
		GmStartParallelLogicalVolumeFilter.hh
		GmTouchableFilterPhysicalVolumeReplicated.hh
		GmEMParticleFilter.hh
		GmTraverseParallelPhysicalVolumeReplicatedFilter.hh
		GmInMassLogicalVolumeFilter.hh
		GmPositionPreXFilter.hh
		GmPrimaryOnAllSecondariesFilter.hh
		GmTraverseLogicalVolumeFilter.hh
		GmGammaFilter.hh
		GmStartLogicalVolumeChildrenFilter.hh
		GmVParallelVolumeConditionFilter.hh
		GmInPhysicalVolumeFilter.hh
	 SOURCES
		GmAncestorsFilter.cc
		GmHistoryOrAncestorsFilter.cc
		GmTouchableFilterRegionChildren.cc
		GmFilterVerbosity.cc
		GmSecondaryFilter.cc
		GmGammaFilter.cc
		plugin.cc
		GmInMassPhysicalVolumeReplicatedFilter.cc
		GmKineticEnergyFilter.cc
		GmProtonFilter.cc
		GmPositionPreZFilter.cc
		GmVertexKineticEnergyFilter.cc
		GmVGeomCondition.cc
		GmVParallelGeomCondition.cc
		GmDirectionThetaFilter.cc
		GmParticleProcessFilter.cc
		GmParentFilter.cc
		GmDeltaEnergyFilter.cc
		GmGeomConditionInParallel.cc
		GmDirectionPreThetaFilter.cc
		GmOnSecondaryFilter.cc
		GmPrimaryOnAllSecondariesFilter.cc
		GmORFilter.cc
		GmTouchableFilterRegion.cc
		GmProcessFilter.cc
		GmInverseFilter.cc
		GmChargedFilter.cc
		GmGeomConditionEnterParallel.cc
		GmDifferentLogicalVolumeFilter.cc
		GmSameLogicalVolumeFilter.cc
		GmDirectionPhiFilter.cc
		GmPositionYFilter.cc
		GmElectronOrPositronFilter.cc
		GmHistoryFilter.cc
		GmStepNumberFilter.cc
		GmCreatorProcessFilter.cc
		GmGeomConditionExit.cc
		GmHistoryAllFilter.cc
		GmPositionPreXFilter.cc
		GmMinRangeCutOutsideVoxelFilter.cc
		GmGeomConditionExitParallel.cc
		GmGeomConditionStart.cc
		GmGeomConditionStartParallel.cc
		GmANDFilter.cc
		GmGeomConditionTraverse.cc
		GmGeomConditionInMass.cc
		GmVProdCutOutsideVoxelFilter.cc
		GmEMParticleFilter.cc
		GmNeutronFilter.cc
		GmInteractionFilter.cc
		GmPositionZFilter.cc
		GmPrimaryFilter.cc
		GmEnergyChangeFilter.cc
		GmGeomConditionEnd.cc
		GmDirectionPrePhiFilter.cc
		GmTouchableFilterPhysicalVolumeChildren.cc
		GmTouchableFilterLogicalVolume.cc
		GmVFilterOfFilters.cc
		GmTouchableFilterTouchable.cc
		GmInMassRegionFilter.cc
		GmPositionPreYFilter.cc
		GmGeomConditionEndParallel.cc
		GmParticleFilter.cc
		GmElectronFilter.cc
		GmPhysicalVolumeFilter.cc
		GmPositionXFilter.cc
		GmTouchableFilterPhysicalVolume.cc
		GmHistoryOrAncestorsFilterForScorer.cc
		GmNumberOfSecondariesFilter.cc
		GmGeomConditionTraverseParallel.cc
		GmGeomConditionIn.cc
		GmInMassLogicalVolumeFilter.cc
		GmTouchableFilterLogicalVolumeChildren.cc
		GmTouchableFilterPhysicalVolumeReplicated.cc
		GmInMassPhysicalVolumeFilter.cc
		GmMaterialFilter.cc
		GmPastHistoryFilter.cc
		GmProdCutAllProcOutsideVoxelFilter.cc
		GmGeomConditionEnter.cc
		GmProdCutOutsideVoxelFilter.cc
		GmTouchableFilterPhysicalVolumeReplicatedChildren.cc
		GmDepositedEnergyFilter.cc
		GmPrimaryOn1SecondaryFilter.cc
		GmVANDFilter.cc
		GmPositronFilter.cc
		GmFilterFromClassifier.cc
		GmPostKineticEnergyFilter.cc
		GmHistoryAncestorsAllFilter.cc
		GmTouchableFilterTouchableChildren.cc
		GmNeutralFilter.cc
		GmXORFilter.cc
	 
	 GRANULAR_DEPENDENCIES
	 GLOBAL_DEPENDENCIES
		${Geant4_libs} 
		${ROOT_LIBRARIES} 
	GamosCore_GamosUtils
	GamosCore_GamosBase_Base
	GamosCore_GamosBase_Classifiers
	GamosCore_GamosUserActionMgr

	LINK_LIBRARIES
)
