# - GamosCore_GamosBase_Filters module build definition

include(UseGamosAtGeant4)
include(UseROOT)

geant4_add_module(GamosCore_GamosBase_Filters
  PUBLIC_HEADERS
    GmEnterLogicalVolumeChildrenFilter.hh
    GmStartRegionChildrenFilter.hh
    GmTouchableFilterPhysicalVolumeChildren.hh
    GmEndLogicalVolumeFilter.hh
    GmDirectionPreThetaFilter.hh
    GmParticleFilter.hh
    GmInMassRegionFilter.hh
    GmOnSecondaryFilter.hh
    GmStepNumberFilter.hh
    GmEndParallelRegionFilter.hh
    GmStartTouchableChildrenFilter.hh
    GmGeomConditionInParallel.hh
    GmKineticEnergyFilter.hh
    GmVParallelVolumeConditionFilter.icc
    GmEnterParallelPhysicalVolumeReplicatedFilter.hh
    GmANDFilter.hh
    GmVProdCutOutsideVoxelFilter.hh
    GmGeomConditionEndParallel.hh
    GmVFilterOfFilters.hh
    GmTraverseLogicalVolumeFilter.hh
    GmMaterialFilter.hh
    GmDeltaEnergyFilter.hh
    GmElectronOrPositronFilter.hh
    GmStartTouchableFilter.hh
    GmHistoryOrAncestorsFilter.hh
    GmMinRangeCutOutsideVoxelFilter.hh
    GmEndRegionChildrenFilter.hh
    GmPrimaryOnAllSecondariesFilter.hh
    GmInParallelRegionFilter.hh
    GmTraverseTouchableFilter.hh
    GmPositionPreYFilter.hh
    GmTraverseParallelLogicalVolumeFilter.hh
    GmStartRegionFilter.hh
    GmEnterRegionFilter.hh
    GmInLogicalVolumeChildrenFilter.hh
    GmTouchableFilterRegion.hh
    GmTraverseParallelPhysicalVolumeFilter.hh
    GmEnterParallelLogicalVolumeFilter.hh
    GmStartPhysicalVolumeChildrenFilter.hh
    GmDepositEnergyFilter.hh
    GmSameLogicalVolumeFilter.hh
    GmEnterPhysicalVolumeChildrenReplicatedFilter.hh
    GmSecondaryFilter.hh
    GmInTouchableChildrenFilter.hh
    GmGeomConditionEnd.hh
    GmEndLogicalVolumeChildrenFilter.hh
    GmDirectionPrePhiFilter.hh
    GmEnergyChangeFilter.hh
    GmStartParallelPhysicalVolumeReplicatedFilter.hh
    GmPastHistoryFilter.hh
    GmInPhysicalVolumeFilter.hh
    GmVANDFilter.hh
    GmGeomConditionInMass.hh
    GmGeomConditionEnter.hh
    GmGeomConditionEnterParallel.hh
    GmHistoryFilter.hh
    GmElectronFilter.hh
    GmTraversePhysicalVolumeChildrenReplicatedFilter.hh
    GmInRegionChildrenFilter.hh
    GmTouchableFilterPhysicalVolumeReplicated.hh
    GmEnterTouchableFilter.hh
    GmTraversePhysicalVolumeChildrenFilter.hh
    GmEnterPhysicalVolumeReplicatedFilter.hh
    GmPostKineticEnergyFilter.hh
    GmExitTouchableChildrenFilter.hh
    GmEndParallelPhysicalVolumeReplicatedFilter.hh
    GmInMassPhysicalVolumeFilter.hh
    GmTouchableFilterTouchableChildren.hh
    GmInLogicalVolumeFilter.hh
    GmNeutralFilter.hh
    GmEndPhysicalVolumeChildrenReplicatedFilter.hh
    GmInPhysicalVolumeReplicatedFilter.hh
    GmInteractionFilter.hh
    GmInParallelPhysicalVolumeFilter.hh
    GmEndRegionFilter.hh
    GmVolumeFilters.hh
    GmTraverseRegionChildrenFilter.hh
    GmVTouchableFilterVolume.hh
    GmExitParallelLogicalVolumeFilter.hh
    GmInParallelPhysicalVolumeReplicatedFilter.hh
    GmExitRegionFilter.hh
    GmParentFilter.hh
    GmTraverseLogicalVolumeChildrenFilter.hh
    GmHistoryOrAncestorsFilterForScorer.hh
    GmORFilter.hh
    GmVGeomCondition.hh
    GmExitParallelRegionFilter.hh
    GmTraverseParallelRegionFilter.hh
    GmStartPhysicalVolumeFilter.hh
    GmGeomConditionTraverse.hh
    GmExitParallelPhysicalVolumeReplicatedFilter.hh
    GmInPhysicalVolumeChildrenFilter.hh
    GmExitPhysicalVolumeReplicatedFilter.hh
    GmExitRegionChildrenFilter.hh
    GmTouchableFilterPhysicalVolumeReplicatedChildren.hh
    GmInverseFilter.hh
    GmFilterFromClassifier.hh
    GmGeomConditionStart.hh
    GmEnterParallelRegionFilter.hh
    GmInMassLogicalVolumeFilter.hh
    GmVParallelGeomCondition.hh
    GmDirectionThetaFilter.hh
    GmExitLogicalVolumeChildrenFilter.hh
    GmAncestorsFilter.hh
    GmTouchableFilterLogicalVolumeChildren.hh
    GmInParallelLogicalVolumeFilter.hh
    GmPrimaryOn1SecondaryFilter.hh
    GmPrimaryFilter.hh
    GmPositionZFilter.hh
    GmEnterRegionChildrenFilter.hh
    GmEnterParallelPhysicalVolumeFilter.hh
    GmParticleProcessFilter.hh
    GmPositionXFilter.hh
    GmInRegionFilter.hh
    GmVertexKineticEnergyFilter.hh
    GmVVolumeConditionFilter.icc
    GmExitLogicalVolumeFilter.hh
    GmInPhysicalVolumeChildrenReplicatedFilter.hh
    GmExitPhysicalVolumeFilter.hh
    GmEMParticleFilter.hh
    GmEndTouchableFilter.hh
    GmEndParallelPhysicalVolumeFilter.hh
    GmStartLogicalVolumeChildrenFilter.hh
    GmEnterPhysicalVolumeChildrenFilter.hh
    GmEnterLogicalVolumeFilter.hh
    GmFilterVerbosity.hh
    GmDirectionPhiFilter.hh
    GmTouchableFilterTouchable.hh
    GmPositionPreZFilter.hh
    GmTraverseRegionFilter.hh
    GmPositionPreXFilter.hh
    GmStartPhysicalVolumeReplicatedFilter.hh
    GmProdCutOutsideVoxelFilter.hh
    GmChargedFilter.hh
    GmStartParallelRegionFilter.hh
    GmNeutronFilter.hh
    GmEnterPhysicalVolumeFilter.hh
    GmProcessFilter.hh
    GmExitPhysicalVolumeChildrenReplicatedFilter.hh
    GmStartLogicalVolumeFilter.hh
    GmTraverseTouchableChildrenFilter.hh
    GmEndPhysicalVolumeReplicatedFilter.hh
    GmCreatorProcessFilter.hh
    GmGeomConditionTraverseParallel.hh
    GmHistoryAncestorsAllFilter.hh
    GmEnterTouchableChildrenFilter.hh
    GmExitTouchableFilter.hh
    GmEndPhysicalVolumeChildrenFilter.hh
    GmHistoryAllFilter.hh
    GmStartPhysicalVolumeChildrenReplicatedFilter.hh
    GmVParallelVolumeConditionFilter.hh
    GmXORFilter.hh
    GmGeomConditionExit.hh
    GmStartParallelPhysicalVolumeFilter.hh
    GmNumberOfSecondariesFilter.hh
    GmGeomConditionExitParallel.hh
    GmGeomConditionStartParallel.hh
    GmExitPhysicalVolumeChildrenFilter.hh
    GmGeomConditionIn.hh
    GmTraversePhysicalVolumeReplicatedFilter.hh
    GmProtonFilter.hh
    GmTouchableFilterLogicalVolume.hh
    GmStartParallelLogicalVolumeFilter.hh
    GmPositronFilter.hh
    GmExitParallelPhysicalVolumeFilter.hh
    GmTraverseParallelPhysicalVolumeReplicatedFilter.hh
    GmPhysicalVolumeFilter.hh
    GmTouchableFilterRegionChildren.hh
    GmPositionYFilter.hh
    GmGammaFilter.hh
    GmVVolumeConditionFilter.hh
    GmTouchableFilterPhysicalVolume.hh
    GmInMassPhysicalVolumeReplicatedFilter.hh
    GmProdCutAllProcOutsideVoxelFilter.hh
    GmEndTouchableChildrenFilter.hh
    GmEndParallelLogicalVolumeFilter.hh
    GmDifferentLogicalVolumeFilter.hh
    GmEndPhysicalVolumeFilter.hh
    GmTraversePhysicalVolumeFilter.hh
    GmInTouchableFilter.hh
  SOURCES
    GmCreatorProcessFilter.cc
    GmGeomConditionEndParallel.cc
    GmDifferentLogicalVolumeFilter.cc
    GmVertexKineticEnergyFilter.cc
    GmPositionXFilter.cc
    GmPositionPreZFilter.cc
    GmParticleProcessFilter.cc
    GmSecondaryFilter.cc
    GmOnSecondaryFilter.cc
    GmKineticEnergyFilter.cc
    GmPhysicalVolumeFilter.cc
    GmInMassRegionFilter.cc
    GmPositionPreYFilter.cc
    GmDirectionPreThetaFilter.cc
    GmXORFilter.cc
    GmGeomConditionEnterParallel.cc
    GmGeomConditionTraverse.cc
    GmProdCutOutsideVoxelFilter.cc
    GmGeomConditionInMass.cc
    GmProtonFilter.cc
    GmTouchableFilterPhysicalVolumeReplicated.cc
    GmTouchableFilterTouchableChildren.cc
    GmVProdCutOutsideVoxelFilter.cc
    GmTouchableFilterRegion.cc
    GmTouchableFilterPhysicalVolumeReplicatedChildren.cc
    GmHistoryFilter.cc
    GmTouchableFilterPhysicalVolumeChildren.cc
    GmInMassPhysicalVolumeFilter.cc
    GmParticleFilter.cc
    GmPositionYFilter.cc
    GmDirectionPhiFilter.cc
    GmTouchableFilterPhysicalVolume.cc
    GmPositronFilter.cc
    GmGeomConditionEnd.cc
    GmHistoryOrAncestorsFilter.cc
    GmEnergyChangeFilter.cc
    GmGeomConditionEnter.cc
    GmEMParticleFilter.cc
    GmPastHistoryFilter.cc
    GmTouchableFilterRegionChildren.cc
    GmTouchableFilterLogicalVolumeChildren.cc
    GmHistoryOrAncestorsFilterForScorer.cc
    GmGammaFilter.cc
    GmNeutronFilter.cc
    GmNumberOfSecondariesFilter.cc
    plugin.cc
    GmGeomConditionIn.cc
    GmNeutralFilter.cc
    GmHistoryAncestorsAllFilter.cc
    GmElectronFilter.cc
    GmInverseFilter.cc
    GmProcessFilter.cc
    GmStepNumberFilter.cc
    GmVANDFilter.cc
    GmElectronOrPositronFilter.cc
    GmInMassPhysicalVolumeReplicatedFilter.cc
    GmGeomConditionExit.cc
    GmParentFilter.cc
    GmORFilter.cc
    GmGeomConditionStart.cc
    GmFilterFromClassifier.cc
    GmPrimaryOn1SecondaryFilter.cc
    GmVParallelGeomCondition.cc
    GmAncestorsFilter.cc
    GmProdCutAllProcOutsideVoxelFilter.cc
    GmANDFilter.cc
    GmSameLogicalVolumeFilter.cc
    GmVFilterOfFilters.cc
    GmPrimaryOnAllSecondariesFilter.cc
    GmGeomConditionInParallel.cc
    GmPositionZFilter.cc
    GmInMassLogicalVolumeFilter.cc
    GmPostKineticEnergyFilter.cc
    GmPrimaryFilter.cc
    GmHistoryAllFilter.cc
    GmGeomConditionTraverseParallel.cc
    GmInteractionFilter.cc
    GmMinRangeCutOutsideVoxelFilter.cc
    GmTouchableFilterTouchable.cc
    GmPositionPreXFilter.cc
    GmFilterVerbosity.cc
    GmDeltaEnergyFilter.cc
    GmChargedFilter.cc
    GmVGeomCondition.cc
    GmDirectionThetaFilter.cc
    GmGeomConditionExitParallel.cc
    GmDirectionPrePhiFilter.cc
    GmMaterialFilter.cc
    GmDepositEnergyFilter.cc
    GmGeomConditionStartParallel.cc
    GmTouchableFilterLogicalVolume.cc
)
# - Add path to generated header
geant4_module_include_directories(GamosCore_GamosBase_Filters
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63>
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63/SEAL_Foundation/SealBase/include>
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63/SEAL_Foundation/SealPlatform/include>
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63/SEAL_Foundation/PluginManager/include>
 PUBLIC  $<BUILD_INTERFACE:${ROOT_BASE_DIR}/include>)

geant4_module_link_libraries(GamosCore_GamosBase_Filters
  PUBLIC
    ${Geant4_libs}
    ${ROOT_LIBRARIES}
    ${SEAL_LIBRARIES} 
    GamosCore_GamosUtils
    GamosCore_GamosBase_Base
    GamosCore_GamosBase_Classifiers
    GamosCore_GamosUserActionMgr
)
