# - GAMOS_analysis_NuclMed_SOE module build definition

include(UseGamosAtGeant4)

geant4_add_module(GAMOS_analysis_NuclMed_SOE
  PUBLIC_HEADERS
    CHit.h
    CUserParameters.h
    C3Vector.h
    CDensityMatrix.h
    CEventManager.h
    CCurrentState.h
    CDataSetManager.h
    C3Matrix.h
    constants.h
    CConeExtension.h
    CEvent.h
    CCone.h
    CPETLine.h
  SOURCES
    constants.cc
    CConeExtension.cc
    CEvent.cc
    CPETLine.cc
    CEventManager.cc
    CHit.cc
    C3Vector.cc
    C3Matrix.cc
    CCone.cc
    CUserParameters.cc
    CCurrentState.cc
    CDensityMatrix.cc
    CDataSetManager.cc
)
geant4_module_link_libraries(GAMOS_analysis_NuclMed_SOE
  PUBLIC
    ${Geant4_libs}
    ${ROOT_LIBRARIES}
    ${SEAL_LIBRARIES} 
)
