include $(GAMOSINSTALL)/config/architecture.gmk

SUBDIRS  = GamosUtils GamosBase/Base GamosUserActionMgr GamosAnalysis GamosData/Management GamosData/Distributions GamosGeometry GamosBase/Classifiers GamosBase/Filters GamosReadDICOM GamosScoring/Management GamosGenerator GamosSD GamosData/Data GamosData/Users  GamosMovement GamosPhysics GamosScoring/Scorers GamosScoring/Printers GamosScoring/PointDetector GamosUtilsUA GamosRunManager GamosApplication 

include $(GAMOSINSTALL)/config/globlib.gmk

