#------------------------------------------------------------------------------
# 
# Module : GamosCore
# Package: GamosBase_Filters
#
#------------------------------------------------------------------------------
# List external includes needed.

# List external includes needed.
include(GamosSetup)
include(UseRoot)

#
# Define the GAMOS Module.
#
include(Geant4MacroDefineModule)
GEANT4_DEFINE_MODULE(NAME GamosCore_GamosBase_Filters

   HEADERS
       GmInParallelPhysicalVolumeReplicatedFilter.hh
       GmExitLogicalVolumeChildrenFilter.hh
       GmEnterTouchableFilter.hh
       GmStartTouchableChildrenFilter.hh
       GmTraversePhysicalVolumeChildrenFilter.hh
       GmEndTouchableFilter.hh
       GmEndParallelLogicalVolumeFilter.hh
       GmEndLogicalVolumeFilter.hh
       GmMaterialFilter.hh
       GmTraverseParallelLogicalVolumeFilter.hh
       GmDirectionThetaFilter.hh
       GmTraversePhysicalVolumeChildrenReplicatedFilter.hh
       GmStartParallelLogicalVolumeFilter.hh
       GmEndPhysicalVolumeFilter.hh
       GmPositionPreXFilter.hh
       GmVertexKineticEnergyFilter.hh
       GmEnterTouchableChildrenFilter.hh
       GmInverseFilter.hh
       GmInteractionFilter.hh
       GmEnterLogicalVolumeChildrenFilter.hh
       GmPhysicalVolumeFilter.hh
       GmHistoryAllFilter.hh
       GmTraversePhysicalVolumeFilter.hh
       GmPrimaryOn1SecondaryFilter.hh
       GmStartPhysicalVolumeChildrenReplicatedFilter.hh
       GmInTouchableFilter.hh
       GmDirectionPhiFilter.hh
       GmEnterPhysicalVolumeChildrenReplicatedFilter.hh
       GmGeomConditionIn.hh
       GmStartLogicalVolumeFilter.hh
       GmGammaFilter.hh
       GmElectronFilter.hh
       GmGeomConditionTraverse.hh
       GmPastHistoryFilter.hh
       GmEnterRegionFilter.hh
       GmTraverseRegionChildrenFilter.hh
       GmExitParallelPhysicalVolumeFilter.hh
       GmVFilterOfFilters.hh
       GmExitLogicalVolumeFilter.hh
       GmFilterFromClassifier.hh
       GmTouchableFilterPhysicalVolumeReplicated.hh
       GmExitRegionFilter.hh
       GmInPhysicalVolumeChildrenFilter.hh
       GmTouchableFilterPhysicalVolume.hh
       GmEnterPhysicalVolumeReplicatedFilter.hh
       GmInRegionFilter.hh
       GmPositionYFilter.hh
       GmInParallelRegionFilter.hh
       GmPostKineticEnergyFilter.hh
       GmChargedFilter.hh
       GmExitRegionChildrenFilter.hh
       GmProcessFilter.hh
       GmParticleProcessFilter.hh
       GmEndLogicalVolumeChildrenFilter.hh
       GmPositionPreZFilter.hh
       GmSameLogicalVolumeFilter.hh
       GmTouchableFilterTouchable.hh
       GmGeomConditionExit.hh
       GmTouchableFilterPhysicalVolumeChildren.hh
       GmExitPhysicalVolumeChildrenFilter.hh
       GmEnterParallelPhysicalVolumeFilter.hh
       GmPositionXFilter.hh
       GmEnterPhysicalVolumeChildrenFilter.hh
       GmStartParallelPhysicalVolumeFilter.hh
       GmInLogicalVolumeChildrenFilter.hh
       GmInLogicalVolumeFilter.hh
       GmEnterParallelLogicalVolumeFilter.hh
       GmTraversePhysicalVolumeReplicatedFilter.hh
       GmTraverseLogicalVolumeFilter.hh
       GmGeomConditionEndParallel.hh
       GmORFilter.hh
       GmVTouchableFilterVolume.hh
       GmHistoryOrAncestorsFilter.hh
       GmGeomConditionTraverseParallel.hh
       GmExitPhysicalVolumeReplicatedFilter.hh
       GmOnSecondaryFilter.hh
       GmInMassPhysicalVolumeFilter.hh
       GmExitParallelRegionFilter.hh
       GmEnterLogicalVolumeFilter.hh
       GmStartPhysicalVolumeChildrenFilter.hh
       GmMinRangeCutOutsideVoxelFilter.hh
       GmStartParallelRegionFilter.hh
       GmEndParallelRegionFilter.hh
       GmEndPhysicalVolumeReplicatedFilter.hh
       GmTraverseParallelRegionFilter.hh
       GmNeutronFilter.hh
       GmVGeomCondition.hh
       GmExitParallelLogicalVolumeFilter.hh
       GmInPhysicalVolumeReplicatedFilter.hh
       GmInMassPhysicalVolumeReplicatedFilter.hh
       GmEndParallelPhysicalVolumeFilter.hh
       GmNumberOfSecondariesFilter.hh
       GmInParallelPhysicalVolumeFilter.hh
       GmEnterRegionChildrenFilter.hh
       GmEnterParallelRegionFilter.hh
       GmInTouchableChildrenFilter.hh
       GmVANDFilter.hh
       GmStepNumberFilter.hh
       GmPositionPreYFilter.hh
       GmXORFilter.hh
       GmInMassLogicalVolumeFilter.hh
       GmGeomConditionInMass.hh
       GmStartPhysicalVolumeReplicatedFilter.hh
       GmInParallelLogicalVolumeFilter.hh
       GmInRegionChildrenFilter.hh
       GmEndRegionChildrenFilter.hh
       GmEndTouchableChildrenFilter.hh
       GmEMParticleFilter.hh
       GmExitTouchableFilter.hh
       GmProdCutAllProcOutsideVoxelFilter.hh
       GmParentFilter.hh
       GmProdCutOutsideVoxelFilter.hh
       GmEndPhysicalVolumeChildrenFilter.hh
       GmVVolumeConditionFilter.hh
       GmTraverseLogicalVolumeChildrenFilter.hh
       GmElectronOrPositronFilter.hh
       GmDirectionPreThetaFilter.hh
       GmVProdCutOutsideVoxelFilter.hh
       GmGeomConditionExitParallel.hh
       GmExitPhysicalVolumeChildrenReplicatedFilter.hh
       GmGeomConditionStartParallel.hh
       GmTouchableFilterLogicalVolume.hh
       GmGeomConditionEnd.hh
       GmExitTouchableChildrenFilter.hh
       GmStartRegionFilter.hh
       GmDirectionPrePhiFilter.hh
       GmStartRegionChildrenFilter.hh
       GmGeomConditionEnterParallel.hh
       GmDeltaEnergyFilter.hh
       GmHistoryAncestorsAllFilter.hh
       GmTraverseRegionFilter.hh
       GmInPhysicalVolumeFilter.hh
       GmTouchableFilterRegion.hh
       GmCreatorProcessFilter.hh
       GmParticleFilter.hh
       GmPrimaryFilter.hh
       GmTraverseTouchableChildrenFilter.hh
       GmEndParallelPhysicalVolumeReplicatedFilter.hh
       GmSecondaryFilter.hh
       GmAncestorsFilter.hh
       GmNeutralFilter.hh
       GmStartPhysicalVolumeFilter.hh
       GmGeomConditionEnter.hh
       GmDifferentLogicalVolumeFilter.hh
       GmEnterParallelPhysicalVolumeReplicatedFilter.hh
       GmTouchableFilterTouchableChildren.hh
       GmHistoryFilter.hh
       GmPrimaryOnAllSecondariesFilter.hh
       GmStartLogicalVolumeChildrenFilter.hh
       GmDepositedEnergyFilter.hh
       GmTraverseParallelPhysicalVolumeFilter.hh
       GmProtonFilter.hh
       GmGeomConditionStart.hh
       GmGeomConditionInParallel.hh
       GmTraverseTouchableFilter.hh
       GmTouchableFilterPhysicalVolumeReplicatedChildren.hh
       GmKineticEnergyFilter.hh
       GmStartTouchableFilter.hh
       GmEndPhysicalVolumeChildrenReplicatedFilter.hh
       GmInMassRegionFilter.hh
       GmPositronFilter.hh
       GmExitPhysicalVolumeFilter.hh
       GmEndRegionFilter.hh
       GmTouchableFilterRegionChildren.hh
       GmInPhysicalVolumeChildrenReplicatedFilter.hh
       GmExitParallelPhysicalVolumeReplicatedFilter.hh
       GmTraverseParallelPhysicalVolumeReplicatedFilter.hh
       GmPositionZFilter.hh
       GmVolumeFilters.hh
       GmStartParallelPhysicalVolumeReplicatedFilter.hh
       GmANDFilter.hh
       GmEnterPhysicalVolumeFilter.hh
       GmTouchableFilterLogicalVolumeChildren.hh

   SOURCES
       GmHistoryFilter.cc
       GmSecondaryFilter.cc
       plugin.cc
       GmVProdCutOutsideVoxelFilter.cc
       GmParticleFilter.cc
       GmProdCutAllProcOutsideVoxelFilter.cc
       GmGeomConditionEnd.cc
       GmCreatorProcessFilter.cc
       GmPrimaryOnAllSecondariesFilter.cc
       GmPositionZFilter.cc
       GmTouchableFilterRegionChildren.cc
       GmPostKineticEnergyFilter.cc
       GmInMassLogicalVolumeFilter.cc
       GmGammaFilter.cc
       GmGeomConditionExit.cc
       GmSameLogicalVolumeFilter.cc
       GmHistoryAllFilter.cc
       GmTouchableFilterLogicalVolume.cc
       GmGeomConditionEndParallel.cc
       GmElectronFilter.cc
       GmHistoryOrAncestorsFilter.cc
       GmDepositedEnergyFilter.cc
       GmEMParticleFilter.cc
       GmTouchableFilterTouchable.cc
       GmDirectionPreThetaFilter.cc
       GmInMassPhysicalVolumeFilter.cc
       GmGeomConditionTraverseParallel.cc
       GmFilterFromClassifier.cc
       GmDifferentLogicalVolumeFilter.cc
       GmGeomConditionStartParallel.cc
       GmDirectionThetaFilter.cc
       GmTouchableFilterRegion.cc
       GmInMassRegionFilter.cc
       GmElectronOrPositronFilter.cc
       GmNeutronFilter.cc
       GmProdCutOutsideVoxelFilter.cc
       GmPositronFilter.cc
       GmPositionPreYFilter.cc
       GmNeutralFilter.cc
       GmVFilterOfFilters.cc
       GmOnSecondaryFilter.cc
       GmNumberOfSecondariesFilter.cc
       GmGeomConditionEnterParallel.cc
       GmMaterialFilter.cc
       GmPositionXFilter.cc
       GmGeomConditionTraverse.cc
       GmVertexKineticEnergyFilter.cc
       GmStepNumberFilter.cc
       GmGeomConditionInMass.cc
       GmMinRangeCutOutsideVoxelFilter.cc
       GmVANDFilter.cc
       GmTouchableFilterPhysicalVolumeReplicated.cc
       GmParticleProcessFilter.cc
       GmPastHistoryFilter.cc
       GmGeomConditionExitParallel.cc
       GmDeltaEnergyFilter.cc
       GmHistoryAncestorsAllFilter.cc
       GmORFilter.cc
       GmProcessFilter.cc
       GmDirectionPhiFilter.cc
       GmGeomConditionEnter.cc
       GmGeomConditionInParallel.cc
       GmPrimaryOn1SecondaryFilter.cc
       GmParentFilter.cc
       GmTouchableFilterPhysicalVolume.cc
       GmAncestorsFilter.cc
       GmGeomConditionIn.cc
       GmPrimaryFilter.cc
       GmGeomConditionStart.cc
       GmProtonFilter.cc
       GmKineticEnergyFilter.cc
       GmTouchableFilterPhysicalVolumeReplicatedChildren.cc
       GmChargedFilter.cc
       GmVGeomCondition.cc
       GmPositionPreZFilter.cc
       GmXORFilter.cc
       GmANDFilter.cc
       GmPhysicalVolumeFilter.cc
       GmDirectionPrePhiFilter.cc
       GmInverseFilter.cc
       GmInteractionFilter.cc
       GmTouchableFilterLogicalVolumeChildren.cc
       GmTouchableFilterTouchableChildren.cc
       GmInMassPhysicalVolumeReplicatedFilter.cc
       GmPositionYFilter.cc
       GmTouchableFilterPhysicalVolumeChildren.cc
       GmPositionPreXFilter.cc
 
   GRANULAR_DEPENDENCIES

   GLOBAL_DEPENDENCIES
    ${Geant4_LIBRARIES}
    ${Root_LIBRARIES}
  GamosCore_GamosBase_Base
  GamosCore_GamosUtils
  GamosCore_GamosGeometry

   LINK_LIBRARIES
)

# List any source specific properties here
