#include "Reflex/PluginService.h"

#include "GmDummyPhysics.hh"
PLUGINSVC_FACTORY(GmDummyPhysics,G4VUserPhysicsList*())

//t #include "GmDNAPhysics.hh"
//t PLUGINSVC_FACTORY(GmDNAPhysics,G4VUserPhysicsList*())

#include "GmG4PhysicsLists.hh"
PLUGINSVC_FACTORY(G4FTFP_BERT,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4FTFP_BERT_HP,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4FTFP_BERT_TRV,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4FTFP_INCLXX,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4FTFP_INCLXX_HP,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4FTF_BIC,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4G4GenericPhysicsList,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4LBE,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QBBC,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QGSP_BERT,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QGSP_BERT_HP,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QGSP_BIC,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QGSP_BIC_HP,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QGSP_FTFP_BERT,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QGSP_INCLXX,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QGSP_INCLXX_HP,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QGS_BIC,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4Shielding,G4VUserPhysicsList*())

PLUGINSVC_FACTORY(G4QGSP_BIC_NHP,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QGSP_BIC_PHP,G4VUserPhysicsList*())
PLUGINSVC_FACTORY(G4QGSP_BIC_AllHP,G4VUserPhysicsList*())
