# - RadioTherapy module build definition

include(UseGamosAtGeant4)
include(UseROOT)

geant4_add_module(RadioTherapy
  PUBLIC_HEADERS
    RTExtraInfoProviderCrossings.hh
    RTPhaseSpaceHistos.hh
    EGSPhspParticle.hh
    RTZRLimitsUA.hh
    RTExtraInfoProviderInteractions.hh
    RTVerbosity.hh
    RTVExtraInfoProviderLong.hh
    RTPSPDoseHistos.hh
    RTReuseAtZPlaneMessenger.hh
    RTGeneratorPSPenelope.hh
    RTMinRangeLimitsStudyUA.hh
    RTProdCutsStudyUA.hh
    iaea_record.hh
    RTCutsStudyFilter.hh
    RTReuseAtZPlaneWithNVoxelUA.hh
    RTGeneratorPhaseSpaceRTPlan.hh
    RTReuseAtZPlaneTrackInfo.hh
    RTExtraInfoProviderZLastNoMaterial.hh
    make_zlib.h
    RTGeneratorPhaseSpace_EGS.hh
    RTReuseAtZPlaneUA.hh
    RTExtraInfoProviderZLast.hh
    iaea_utilities.hh
    RTClassifierByEILong.hh
    RTVZRLimitsUA.hh
    iaea_config.hh
    RTExtraInfoTrackInfo.hh
    RTExtraInfoProviderOrigin.hh
    RTPhaseSpaceMessenger.hh
    RTGeneratorPhaseSpace.hh
    RTPhaseSpaceGenerator.hh
    RTExtraInfoProviderZOrigin.hh
    RTVExtraInfoProvider.hh
    RTPhaseSpace_EGSUA.hh
    RTReuseAtZPlaneProcess.hh
    RTVExtraInfoProviderFloat.hh
    RTPSPDoseHistosVector.hh
    iaea_header.hh
    RTVClassifierByExtraInfo.hh
    RTZRLimitsAutoUA.hh
    RTPhaseSpaceUA.hh
    RTFilterByEILong.hh
    RTVExtraInfoProviderLongByRegion.hh
    RTExtraInfoMgr.hh
    RTPhaseSpace_extUA.hh
  SOURCES
    RTPSPDoseHistos.cc
    RTReuseAtZPlaneMessenger.cc
    RTExtraInfoProviderZOrigin.cc
    RTReuseAtZPlaneProcess.cc
    RTClassifierByEILong.cc
    RTPhaseSpaceUA.cc
    RTZRLimitsAutoUA.cc
    iaea_utilities.cc
    RTFilterByEILong.cc
    RTGeneratorPhaseSpace_EGS.cc
    RTExtraInfoProviderZLastNoMaterial.cc
    RTReuseAtZPlaneWithNVoxelUA.cc
    EGSPhspParticle.cc
    RTPhaseSpace_EGSUA.cc
    RTPhaseSpace_extUA.cc
    RTPhaseSpaceHistos.cc
    zlib.h
    RTExtraInfoProviderCrossings.cc
    RTVerbosity.cc
    iaea_header.cc
    plugin.cc
    RTReuseAtZPlaneTrackInfo.cc
    RTPSPDoseHistos.cc.old
    RTExtraInfoProviderInteractions.cc
    RTVExtraInfoProviderFloat.cc
    RTProdCutsStudyUA.cc
    RTPSPDoseHistosVector.cc
    RTGeneratorPSPenelope.cc
    RTVExtraInfoProviderLong.cc
    RTVExtraInfoProviderLongByRegion.cc
    RTGeneratorPhaseSpaceRTPlan.cc
    RTMinRangeLimitsStudyUA.cc
    RTReuseAtZPlaneUA.cc
    RTExtraInfoProviderOrigin.cc
    RTVExtraInfoProvider.cc
    RTCutsStudyFilter.cc
    RTExtraInfoMgr.cc
    RTExtraInfoProviderZLast.cc
    RTZRLimitsUA.cc
    RTGeneratorPhaseSpace.cc
    iaea_record.cc
    RTVZRLimitsUA.cc
    RTExtraInfoTrackInfo.cc
    RTVClassifierByExtraInfo.cc
)
# - Add path to generated header
geant4_module_include_directories(RadioTherapy
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63>
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63/SEAL_Foundation/SealBase/include>
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63/SEAL_Foundation/SealPlatform/include>
 PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/source/GAMOS63/SEAL_Foundation/PluginManager/include>
 PUBLIC  $<BUILD_INTERFACE:${ROOT_BASE_DIR}/include>)

geant4_module_link_libraries(RadioTherapy
  PUBLIC
    ${Geant4_libs}
    ${ROOT_LIBRARIES}
    ${SEAL_LIBRARIES} 
    GamosCore_GamosBase_Base
    GamosCore_GamosSD
    GamosCore_GamosGenerator
    GamosCore_GamosUserActionMgr
    GamosCore_GamosUtils
    GamosCore_GamosReadDICOM
    GamosCore_GamosUtilsUA
    GamosCore_GamosScoring_Management
    GamosCore_GamosPhysics_Cuts
)
