#------------------------------------------------------------------------------
# 
# Module : SEAL_Foundation_SealBase
# Package: 
#
#------------------------------------------------------------------------------
set(CMAKE_VERBOSE_MAKEFILE ON)
include(Geant4MacroDefineModule)
include_directories(${CMAKE_SOURCE_DIR}/source)
include_directories(${CMAKE_SOURCE_DIR}/source/SEAL_Foundation/PluginManager)
include_directories(${CMAKE_SOURCE_DIR}/source/SEAL_Foundation/SealPlatform)
include_directories(${CMAKE_SOURCE_DIR}/source/SEAL_Foundation/SealBase)
#
# Define the GAMOS Module.
#
GEANT4_DEFINE_MODULE(NAME SEAL_Foundation_SealBase
	 HEADERS
		SysErr.h
		Macros.h
		File.h
		Regexp.h
		RegexpError.h
		SubProcess.h
		IOError.h
		ProcessInfo.h
		IOFlags.h
		DirIterator.h
		Signal.h
		FileNameLock.h
		FileAcl.h
		IOChannelPair.h
		IOSelector.h
		RegexpMatch.h
		Storage.h
		FileSystemError.h
		TempFile.h
		UUID.h
		Socket.h
		BitTraits.h
		Pipe.h
		StringList.h
		IOSelectEvent.h
		ShellEnvironment.h
		FilenameError.h
		IOInput.h
		config.h
		Argz.h
		BitIterator.h
		IOStatus.h
		Time.h
		Range.h
		Hook.h
		PipeCmd.h
		AutoLoad.h
		IOOutput.h
		SystemError.h
		Log.h
		NetworkError.h
		TimeConst.h
		iosfwd.h
		LocalSocket.h
		Error.h
		SystemInfo.h
		BitPattern.h
		Unwind.h
		StringFormat.h
		IOBuffer.h
		FileError.h
		SharedLibraryError.h
		ResourceInfo.h
		StringOps.h
		NamedPipeServer.h
		SubProcessError.h
		IOSelectCB.h
		FileMapping.h
		FileLock.h
		LowMemoryPool.h
		Filename.h
		XTypeInfo.h
		LocalServerSocket.h
		UUIDError.h
		Callback.h
		InetSocket.h
		HostInfo.h
		InetServerSocket.h
		SocketConst.h
		IntBits.h
		MapIterator.h
		PODVector.h
		MultiMethod.h
		HookList.h
		IntTraits.h
		IOChannel.h
		FileMappingError.h
		SharedLibrary.h
		Environment.h
		SaveErrno.h
		LongLong.h
		UserInfo.h
		SocketPair.h
		DebugAids.h
		Sequence.h
		BitOps.h
		TimeInfo.h
		SearchPath.h
	 SOURCES
		FileMapping.cc
		Windows.cc
		IOInput.cc
		Socket.cc
		LogFile.cc
		FilenameError.cc
		Pipe.cc
		SystemInfo.cc
		SharedLibrary.cc
		LogStderr.cc
		LocalServerSocket.cc
		WindowsSocket.cc
		Environment.cc
		IOError.cc
		Storage.cc
		IntTraits.cc
		FileNameLock.cc
		IOChannel.cc
		WindowsSubProcess.cc
		UnixSubProcess.cc
		WindowsFileMapping.cc
		IOSelectMethod.h
		UnixNamedPipeServer.cc
		BuildFile
		SubProcessError.cc
		IOSelectSig.h
		IOSelectFdMap.h
		SubProcess.cc
		LowMemoryPool.cc
		LogSink.cc
		UnixSocket.cc
		SearchPath.cc
		IOSelectSelect.cc
		UnixFileMapping.cc
		UnixIOStatus.cc
		UserInfo.cc
		SystemError.cc
		UnixDirIterator.cc
		IOSelectWindows.cc
		IOSelectDevPoll.h
		TempFile.cc
		WindowsFilename.cc
		DirIterator.cc
		LogSocket.cc
		IOSelectSelect.h
		UnixTempFile.cc
		IOChannelTransfer.cc
		SocketPair.cc
		UnixPipe.cc
		WindowsIOStatus.cc
		WindowsNamedPipeServer.cc
		LogConsole.cc
		WindowsTempFile.cc
		File.cc
		Signal.cc
		WindowsPipe.cc
		IOSelectMethod.cc
		StringFormat.cc
		IOSelectPoll.cc
		Time.cc
		Log.cc
		ShellEnvironment.cc
		IOSelectKqueue.h
		FileSystemError.cc
		Filename.cc
		FileAcl.cc
		ProcessInfo.cc
		SharedLibraryError.cc
		IOSelec tFdMap.cc
		LogPipe.cc
		WindowsUserInfo.cc
		IOSelectDevPoll.cc
		InetSocket.cc
		IOSelectKqueue.cc
		WindowsFile.cc
		NamedPipeServer.cc
		NetworkError.cc
		IOSelectWindows.h
		readme.notes
		RegexpError.cc
		HostInfo.cc
		IOSelectSig.cc
		Error.cc
		StringHack.h
		FileLock.cc
		MultiMethod.cc
		WindowsDirIterator.cc
		XTypeInfo.cc
		IOSelectRequest.h
		FileMappingError.cc
		AutoLoad.cc
		Argz.cc
		PipeCmd.cc
		LongLong.cc
		InetServerSocket.cc
		UnixSocketPair.cc
		UnixFileAcl.cc
		IOSelector.cc
		UnixFileLock.cc
		RegexpMatch.cc
		WindowsFileAcl.cc
		IOSelectSigFd.cc
		DebugAids.cc
		StringOps.cc
		IOChannelPair.cc
		UnixIOChannel.cc
		FileError.cc
		WindowsSocketPair.cc
		IOSelectSigFd.h
		Regexp.cc
		WindowsIOChannel.cc
		IOOutput.cc
		UnixFile.cc
		IOStatus.cc
		IOSelectPoll.h
		UnixFilename.cc
		ResourceInfo.cc
		SocketConst.cc
		TimeInfo.cc
		LocalSocket.cc
		UnixUserInfo.cc
		WindowsFileLock.cc
	 
	 GLOBAL_DEPENDENCIES
		${Geant4_LIBRARIES} 
		${ROOT_LIBRARIES} 

	LINK_LIBRARIES
)
