# - GAMOS_analysis_DICOM_DICOM2G4 module build definition

include(UseGamosAtGeant4)

geant4_add_module(GAMOS_analysis_DICOM_DICOM2G4
  PUBLIC_HEADERS
    DicomBeamDevicePos.hh
    DicomBeamCompensator.hh
    DicomReaderRTPlan.hh
    DicomBeamWedge.hh
    DicomBeamDevice.hh
    DicomBeamRTControlPoint.hh
    DicomBeamDeviceBLD.hh
    Dicom2G4FileMgr.hh
    DicomVBeamDevice.hh
    DicomVBeamRTControlPoint.hh
    DicomReaderRTIonPlan.hh
    DicomBeamRTIonControlPoint.hh
    DicomBeamBlock.hh
    DicomBeam.hh
  SOURCES
    DicomBeamBlock.cc
    DicomBeam.cc
    DicomBeamDevice.cc
    DicomBeamCompensator.cc
    DicomVBeamDevice.cc
    DicomReaderNM.cc.old
    DicomBeamWedge.cc
    DicomBeamDeviceBLD.cc
    DicomReaderRTIonPlan.cc
    DicomReaderRTPlan.cc
    DicomBeamRTIonControlPoint.cc
    DicomBeamDevicePos.cc
    DicomBeamRTControlPoint.cc
    DicomVBeamRTControlPoint.cc
    Dicom2G4FileMgr.cc
)
geant4_module_link_libraries(GAMOS_analysis_DICOM_DICOM2G4
  PUBLIC
    ${Geant4_libs}
    ${ROOT_LIBRARIES}
    DICOMReaders
    DICOMBase
    ${SEAL_LIBRARIES} 
)
