# - GAMOS_analysis_Shielding_sumScores module build definition

include(UseGamosAtGeant4)

geant4_add_module(GAMOS_analysis_Shielding_sumScores
  PUBLIC_HEADERS
    ReadScores.icc
    FileData.hh
    TextScorerData.hh
    MCNPFileData.hh
    TextFileData.hh
    ScoreData.hh
    MCNPTallyData.hh
    MCNPVTallierData.hh
    MCNPTallierFNData.hh
    ScorerData.hh
    GAMOSFileData.hh
    GAMOSScoreData.hh
    TextScoreData.hh
    MCNPTallierF5Data.hh
    GAMOSScorerData.hh
  SOURCES
    TextScoreData.cc
    MCNPTallierFNData.cc
    ScoreData.cc
    ScorerData.cc
    GAMOSScoreData.cc
    GAMOSScorerData.cc
    TextScorerData.cc
    MCNPTallyData.cc
    MCNPTallierF5Data.cc
    MCNPVTallierData.cc
    MCNPFileData.cc
    GAMOSFileData.cc
    FileData.cc
    TextFileData.cc
)
geant4_module_link_libraries(GAMOS_analysis_Shielding_sumScores
  PUBLIC
    ${Geant4_libs}
    ${ROOT_LIBRARIES}
    ${SEAL_LIBRARIES} 
)
