#------------------------------------------------------------------------------
# Module : GamosGeometry
# Package: GamosCore_GamosGeometry
#
#------------------------------------------------------------------------------
#
set(CMAKE_VERBOSE_MAKEFILE ON)
include_directories(${CMAKE_SOURCE_DIR}/source)
include_directories(${CMAKE_SOURCE_DIR}/include)
#
# Define the GEANT4 Module.
include(UseGamosAtGeant4)
#
GEANT4_DEFINE_MODULE(NAME GamosCore_GamosGeometry
	 HEADERS
		GmOpticalPropertiesMgr.hh
		GmReadPhantomGeometry.hh
		GmModuleRangeModulator.hh
		GmDICOMIntersectVolume.hh
		GmGeomTextLineProcessor.hh
		GmSolid.hh
		GmUniformEMField.hh
		GmGeometryFactory.hh
		GmParallelWorldCreator.hh
		GmModuleJaws.hh
		GmGeomTextDetectorBuilder.hh
		GmGeomTextDumperUA.hh
		GmModuleMLC.hh
		GmGeomUseMateDetectorBuilder.hh
		GmDetectorPart.hh
		GmParallelWorld.hh
		GmModuleMgr.hh
		GmUniformElectricField.hh
		GmRegionCutsMgr.hh
		GmRegionData.hh
		GmGeometryUtils.hh
		GmGeometryFromText.hh
		GmGeometryMessenger.hh
		GmGeomVerbosity.hh
		GmUniformMagField.hh
		GmDetector.hh
		GmGeometryUseMaterials.hh
		GmVModule.hh
		GmTouchable.hh
	 SOURCES
		GmGeomTextDetectorBuilder.cc
		plugin.cc
		GmRegionCutsMgr.cc
		GmGeomUseMateDetectorBuilder.cc
		GmMaterialList.icc
		GmDICOMIntersectVolume.cc
		GmGeomTextLineProcessor.cc
		GmGeomTextDumperUA.cc
		GmUniformElectricField.cc
		GmModuleMgr.cc
		GmModuleJaws.cc
		GmGeomVerbosity.cc
		GmUniformMagField.cc
		GmReadPhantomGeometry.cc
		GmModuleRangeModulator.cc
		GmVModule.cc
		GmParallelWorld.cc
		GmGeometryFromText.cc
		GmModuleMLC.cc
		GmDetector.cc
		GmTouchable.cc
		GmGeometryUtils.cc
		GmUniformEMField.cc
		GmModuleMLC.cc.old
		GmSolid.cc
		GmGeometryFactory.cc
		GmParallelWorldCreator.cc
		GmOpticalPropertiesMgr.cc
		GmRegionData.cc
		GmGeometryMessenger.cc
		GmGeometryUseMaterials.cc
	 
	 GRANULAR_DEPENDENCIES
	 GLOBAL_DEPENDENCIES
		${Geant4_libs} 
		${ROOT_LIBRARIES} 
	GamosCore_GamosBase_Base
	GamosCore_GamosUtils
	GamosCore_GamosUserActionMgr
	GamosCore_GamosData_Distributions
		${SEAL_LIBRARIES} 

	LINK_LIBRARIES
)
